version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres_nest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: ozzyDB
    volumes:
      - pgdata:/var/lib/prostgresql/data

volumes:
  pgdata:
